repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: flake8
        args: [--max-line-length=120, --ignore=F841]
      - id: check-yaml
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]